#!/usr/bin/env bash
set -exo pipefail

# default versions
memtest_version=${memtest_version:-"6.01"}
unzip_version=${unzip_version:-"6.0-r13"}
wget_version=${wget_version:-"1.21.3-r2"}

# default path to save the setup-memtest binaries
export MEMTEST_PATH=${mtest_path:-"/usr/share/mt86plus"}

# install required system packages
apk add --no-cache unzip="${unzip_version}" wget="${wget_version}"

# download memtest86+ and its checksum
wget -q "https://www.memtest.org/download/v$memtest_version/mt86plus_$memtest_version.binaries.zip"
wget -q "https://www.memtest.org/download/v$memtest_version/sha256sum.txt"

# validate the checksum or fail the docker build
grep "mt86plus_$memtest_version.binaries.zip" "sha256sum.txt" | sha256sum -c
rm "sha256sum.txt"

# extract memtest86+ and remove the ZIP file
mkdir -p "$MEMTEST_PATH"
unzip "mt86plus_$memtest_version.binaries.zip" -d "$MEMTEST_PATH"
rm "mt86plus_$memtest_version.binaries.zip"
