#!/usr/bin/env bash
set -exo pipefail

# syslinux installed files
syslinux_path=${syslinux_path:-"/usr/share/syslinux"}

# published files
tftp_public_path=${tftp_public_path:-"/home/tftp/public"}

# syslinux
ln -s "$syslinux_path/ldlinux.c32"  "$tftp_public_path"
ln -s "$syslinux_path/libutil.c32"  "$tftp_public_path"
ln -s "$syslinux_path/menu.c32"     "$tftp_public_path"
ln -s "$syslinux_path/pxelinux.0"   "$tftp_public_path"

# memtest
mkdir "$tftp_public_path/mt86plus"
ln -s "$MEMTEST_PATH/memtest32.bin" "$tftp_public_path/mt86plus"
